// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsig.proto

package dsig;

public final class Dsig {
  private Dsig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SignatureOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 version = 1;
    /**
     * <code>optional uint32 version = 1;</code>
     *
     * <pre>
     *版本 默认1
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional uint32 version = 1;</code>
     *
     * <pre>
     *版本 默认1
     * </pre>
     */
    int getVersion();

    // optional uint64 time = 6;
    /**
     * <code>optional uint64 time = 6;</code>
     *
     * <pre>
     *序号2-5保留
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>optional uint64 time = 6;</code>
     *
     * <pre>
     *序号2-5保留
     * </pre>
     */
    long getTime();

    // optional uint64 mid = 7;
    /**
     * <code>optional uint64 mid = 7;</code>
     *
     * <pre>
     *客户id，用区分不同的客户
     * </pre>
     */
    boolean hasMid();
    /**
     * <code>optional uint64 mid = 7;</code>
     *
     * <pre>
     *客户id，用区分不同的客户
     * </pre>
     */
    long getMid();

    // optional uint64 sub_mid = 8;
    /**
     * <code>optional uint64 sub_mid = 8;</code>
     *
     * <pre>
     *客户子id，留给用户去区分自己的客户
     * </pre>
     */
    boolean hasSubMid();
    /**
     * <code>optional uint64 sub_mid = 8;</code>
     *
     * <pre>
     *客户子id，留给用户去区分自己的客户
     * </pre>
     */
    long getSubMid();

    // optional uint64 tid = 9;
    /**
     * <code>optional uint64 tid = 9;</code>
     *
     * <pre>
     *临时设备id
     * </pre>
     */
    boolean hasTid();
    /**
     * <code>optional uint64 tid = 9;</code>
     *
     * <pre>
     *临时设备id
     * </pre>
     */
    long getTid();

    // optional uint64 did = 15;
    /**
     * <code>optional uint64 did = 15;</code>
     *
     * <pre>
     *设备id，设备唯一的身份识别号码
     * </pre>
     */
    boolean hasDid();
    /**
     * <code>optional uint64 did = 15;</code>
     *
     * <pre>
     *设备id，设备唯一的身份识别号码
     * </pre>
     */
    long getDid();
  }
  /**
   * Protobuf type {@code dsig.Signature}
   */
  public static final class Signature extends
      com.google.protobuf.GeneratedMessage
      implements SignatureOrBuilder {
    // Use Signature.newBuilder() to construct.
    private Signature(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Signature(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Signature defaultInstance;
    public static Signature getDefaultInstance() {
      return defaultInstance;
    }

    public Signature getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Signature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000002;
              time_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000004;
              mid_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000008;
              subMid_ = input.readUInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000010;
              tid_ = input.readUInt64();
              break;
            }
            case 120: {
              bitField0_ |= 0x00000020;
              did_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dsig.Dsig.internal_static_dsig_Signature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dsig.Dsig.internal_static_dsig_Signature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dsig.Dsig.Signature.class, dsig.Dsig.Signature.Builder.class);
    }

    public static com.google.protobuf.Parser<Signature> PARSER =
        new com.google.protobuf.AbstractParser<Signature>() {
      public Signature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Signature(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Signature> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>optional uint32 version = 1;</code>
     *
     * <pre>
     *版本 默认1
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 version = 1;</code>
     *
     * <pre>
     *版本 默认1
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    // optional uint64 time = 6;
    public static final int TIME_FIELD_NUMBER = 6;
    private long time_;
    /**
     * <code>optional uint64 time = 6;</code>
     *
     * <pre>
     *序号2-5保留
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 time = 6;</code>
     *
     * <pre>
     *序号2-5保留
     * </pre>
     */
    public long getTime() {
      return time_;
    }

    // optional uint64 mid = 7;
    public static final int MID_FIELD_NUMBER = 7;
    private long mid_;
    /**
     * <code>optional uint64 mid = 7;</code>
     *
     * <pre>
     *客户id，用区分不同的客户
     * </pre>
     */
    public boolean hasMid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 mid = 7;</code>
     *
     * <pre>
     *客户id，用区分不同的客户
     * </pre>
     */
    public long getMid() {
      return mid_;
    }

    // optional uint64 sub_mid = 8;
    public static final int SUB_MID_FIELD_NUMBER = 8;
    private long subMid_;
    /**
     * <code>optional uint64 sub_mid = 8;</code>
     *
     * <pre>
     *客户子id，留给用户去区分自己的客户
     * </pre>
     */
    public boolean hasSubMid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 sub_mid = 8;</code>
     *
     * <pre>
     *客户子id，留给用户去区分自己的客户
     * </pre>
     */
    public long getSubMid() {
      return subMid_;
    }

    // optional uint64 tid = 9;
    public static final int TID_FIELD_NUMBER = 9;
    private long tid_;
    /**
     * <code>optional uint64 tid = 9;</code>
     *
     * <pre>
     *临时设备id
     * </pre>
     */
    public boolean hasTid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 tid = 9;</code>
     *
     * <pre>
     *临时设备id
     * </pre>
     */
    public long getTid() {
      return tid_;
    }

    // optional uint64 did = 15;
    public static final int DID_FIELD_NUMBER = 15;
    private long did_;
    /**
     * <code>optional uint64 did = 15;</code>
     *
     * <pre>
     *设备id，设备唯一的身份识别号码
     * </pre>
     */
    public boolean hasDid() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 did = 15;</code>
     *
     * <pre>
     *设备id，设备唯一的身份识别号码
     * </pre>
     */
    public long getDid() {
      return did_;
    }

    private void initFields() {
      version_ = 0;
      time_ = 0L;
      mid_ = 0L;
      subMid_ = 0L;
      tid_ = 0L;
      did_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(6, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(7, mid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(8, subMid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(9, tid_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(15, did_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, mid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, subMid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, tid_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(15, did_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static dsig.Dsig.Signature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsig.Dsig.Signature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsig.Dsig.Signature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dsig.Dsig.Signature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dsig.Dsig.Signature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dsig.Dsig.Signature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static dsig.Dsig.Signature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static dsig.Dsig.Signature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static dsig.Dsig.Signature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dsig.Dsig.Signature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dsig.Dsig.Signature prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dsig.Signature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements dsig.Dsig.SignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dsig.Dsig.internal_static_dsig_Signature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dsig.Dsig.internal_static_dsig_Signature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dsig.Dsig.Signature.class, dsig.Dsig.Signature.Builder.class);
      }

      // Construct using dsig.Dsig.Signature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        mid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        subMid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        tid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        did_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dsig.Dsig.internal_static_dsig_Signature_descriptor;
      }

      public dsig.Dsig.Signature getDefaultInstanceForType() {
        return dsig.Dsig.Signature.getDefaultInstance();
      }

      public dsig.Dsig.Signature build() {
        dsig.Dsig.Signature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dsig.Dsig.Signature buildPartial() {
        dsig.Dsig.Signature result = new dsig.Dsig.Signature(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mid_ = mid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.subMid_ = subMid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.tid_ = tid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.did_ = did_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dsig.Dsig.Signature) {
          return mergeFrom((dsig.Dsig.Signature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dsig.Dsig.Signature other) {
        if (other == dsig.Dsig.Signature.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasMid()) {
          setMid(other.getMid());
        }
        if (other.hasSubMid()) {
          setSubMid(other.getSubMid());
        }
        if (other.hasTid()) {
          setTid(other.getTid());
        }
        if (other.hasDid()) {
          setDid(other.getDid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dsig.Dsig.Signature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dsig.Dsig.Signature) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 version = 1;
      private int version_ ;
      /**
       * <code>optional uint32 version = 1;</code>
       *
       * <pre>
       *版本 默认1
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 version = 1;</code>
       *
       * <pre>
       *版本 默认1
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional uint32 version = 1;</code>
       *
       * <pre>
       *版本 默认1
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 version = 1;</code>
       *
       * <pre>
       *版本 默认1
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // optional uint64 time = 6;
      private long time_ ;
      /**
       * <code>optional uint64 time = 6;</code>
       *
       * <pre>
       *序号2-5保留
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 time = 6;</code>
       *
       * <pre>
       *序号2-5保留
       * </pre>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional uint64 time = 6;</code>
       *
       * <pre>
       *序号2-5保留
       * </pre>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 time = 6;</code>
       *
       * <pre>
       *序号2-5保留
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 mid = 7;
      private long mid_ ;
      /**
       * <code>optional uint64 mid = 7;</code>
       *
       * <pre>
       *客户id，用区分不同的客户
       * </pre>
       */
      public boolean hasMid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 mid = 7;</code>
       *
       * <pre>
       *客户id，用区分不同的客户
       * </pre>
       */
      public long getMid() {
        return mid_;
      }
      /**
       * <code>optional uint64 mid = 7;</code>
       *
       * <pre>
       *客户id，用区分不同的客户
       * </pre>
       */
      public Builder setMid(long value) {
        bitField0_ |= 0x00000004;
        mid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 mid = 7;</code>
       *
       * <pre>
       *客户id，用区分不同的客户
       * </pre>
       */
      public Builder clearMid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mid_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 sub_mid = 8;
      private long subMid_ ;
      /**
       * <code>optional uint64 sub_mid = 8;</code>
       *
       * <pre>
       *客户子id，留给用户去区分自己的客户
       * </pre>
       */
      public boolean hasSubMid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 sub_mid = 8;</code>
       *
       * <pre>
       *客户子id，留给用户去区分自己的客户
       * </pre>
       */
      public long getSubMid() {
        return subMid_;
      }
      /**
       * <code>optional uint64 sub_mid = 8;</code>
       *
       * <pre>
       *客户子id，留给用户去区分自己的客户
       * </pre>
       */
      public Builder setSubMid(long value) {
        bitField0_ |= 0x00000008;
        subMid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sub_mid = 8;</code>
       *
       * <pre>
       *客户子id，留给用户去区分自己的客户
       * </pre>
       */
      public Builder clearSubMid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        subMid_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 tid = 9;
      private long tid_ ;
      /**
       * <code>optional uint64 tid = 9;</code>
       *
       * <pre>
       *临时设备id
       * </pre>
       */
      public boolean hasTid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 tid = 9;</code>
       *
       * <pre>
       *临时设备id
       * </pre>
       */
      public long getTid() {
        return tid_;
      }
      /**
       * <code>optional uint64 tid = 9;</code>
       *
       * <pre>
       *临时设备id
       * </pre>
       */
      public Builder setTid(long value) {
        bitField0_ |= 0x00000010;
        tid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 tid = 9;</code>
       *
       * <pre>
       *临时设备id
       * </pre>
       */
      public Builder clearTid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tid_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 did = 15;
      private long did_ ;
      /**
       * <code>optional uint64 did = 15;</code>
       *
       * <pre>
       *设备id，设备唯一的身份识别号码
       * </pre>
       */
      public boolean hasDid() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 did = 15;</code>
       *
       * <pre>
       *设备id，设备唯一的身份识别号码
       * </pre>
       */
      public long getDid() {
        return did_;
      }
      /**
       * <code>optional uint64 did = 15;</code>
       *
       * <pre>
       *设备id，设备唯一的身份识别号码
       * </pre>
       */
      public Builder setDid(long value) {
        bitField0_ |= 0x00000020;
        did_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 did = 15;</code>
       *
       * <pre>
       *设备id，设备唯一的身份识别号码
       * </pre>
       */
      public Builder clearDid() {
        bitField0_ = (bitField0_ & ~0x00000020);
        did_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dsig.Signature)
    }

    static {
      defaultInstance = new Signature(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dsig.Signature)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dsig_Signature_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dsig_Signature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndsig.proto\022\004dsig\"b\n\tSignature\022\017\n\007versi" +
      "on\030\001 \001(\r\022\014\n\004time\030\006 \001(\004\022\013\n\003mid\030\007 \001(\004\022\017\n\007s" +
      "ub_mid\030\010 \001(\004\022\013\n\003tid\030\t \001(\004\022\013\n\003did\030\017 \001(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dsig_Signature_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dsig_Signature_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dsig_Signature_descriptor,
              new java.lang.String[] { "Version", "Time", "Mid", "SubMid", "Tid", "Did", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
